name: Build PTOID Installer

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Install backend dependencies
      run: |
        cd backend
        python -m venv venv
        venv\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build installer
      run: |
        cd frontend
        npm run dist

    - name: Skip tests (no test folder yet)
      run: echo "No tests defined — skipping test step."
